[package]
name = "server"
version = "0.1.0"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]

[dependencies]
lobby = { path = "../lobby" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
vec_map = "*"
